name: Deploy in dev branch
on:
  push:
    branches:
      - main # Trigger only on the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "22.13.1"

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws_key.pem
          chmod 400 ~/.ssh/aws_key.pem
          
      - name: Add EC2 to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEV_IP }} >> ~/.ssh/known_hosts  
      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws_key.pem ubuntu@${{ secrets.DEV_IP }} << 'EOF'
            cd Devops-CI-CD-
            git pull origin main
            node -v 
            pnpm install
            pm2 restart web || pm2 restart index
          EOF
      